name: build-astro-page

on:
  issue_comment:
    types: [created, deleted]
  issues:
    types: [opened, edited, deleted]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build_on_general_events:
    if: ${{ contains(fromJson('["issue_comment", "workflow_dispatch"]'), github.event_name) }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Init
        run: yarn
      - name: Force Install Sharp
        run: yarn add sharp --ignore-engines
      - name: Build
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: yarn build
      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: page
          FOLDER: dist
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build_on_modifying_issues:
    if: ${{ github.event_name == 'issues' && contains(github.event.issue.labels.*.name, 'state:published') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Init
        run: yarn
      - name: Force Install Sharp
        run: yarn add sharp --ignore-engines
      - name: Build
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: yarn build
      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: page
          FOLDER: dist
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
