name: build-astro-page

on:
  push:
    branches:
      - main
  issue_comment:
    types: [created, deleted]
  issues:
    types: [labeled, unlabeled]
  workflow_dispatch:

jobs:
  main:
    if: ${{ contains(fromJson('["push", "workflow_dispatch", "issue_comment"]'), github.event_name) || github.event.label.name == 'state:published' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Init
        run: yarn
      - name: Build
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: yarn build
      - name: Deploy
        uses: s0/git-publish-subdir-action@v2.3.0
        env:
          REPO: self
          BRANCH: page
          FOLDER: dist
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
